// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// PetType - the type of pets allowed
type PetType string

const (
	PetTypeDog PetType = "dog"
	PetTypeCat PetType = "cat"
)

func (e PetType) ToPointer() *PetType {
	return &e
}

func (e *PetType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "dog":
		fallthrough
	case "cat":
		*e = PetType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PetType: %v", v)
	}
}
